# Generated by Django 3.1.3 on 2021-01-14 08:34

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, unique=True, unique_for_date='created')),
                ('created', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(null=True, verbose_name='內容')),
                ('attachment', models.FileField(upload_to='healthes/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='authority',
            field=models.CharField(choices=[('admin', '管理者'), ('general', '一般民眾')], default='resident', max_length=20, verbose_name='身分'),
        ),
    ]
