# Generated by Django 3.1.3 on 2021-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210114_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='category',
            field=models.CharField(default='', max_length=32),
        ),
    ]
