# Generated by Django 3.1.3 on 2021-02-02 06:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210202_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, null=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=32, null=True)),
                ('category', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(null=True, verbose_name='內容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
