# Generated by Django 3.1.3 on 2021-02-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210202_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='attachment',
        ),
    ]
