# Generated by Django 3.1.3 on 2021-02-07 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_reading_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to=settings.AUTH_USER_MODEL),
        ),
    ]
