# Generated by Django 3.1.3 on 2021-02-17 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_reading_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='活動名稱')),
                ('content', models.TextField(verbose_name='活動內容')),
                ('point', models.IntegerField(default=0, verbose_name='點數')),
            ],
        ),
        migrations.CreateModel(
            name='myActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_date', models.DateField()),
                ('content', models.TextField(verbose_name='活動內容')),
                ('point', models.IntegerField(default=0, verbose_name='點數')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_activity', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
        ),
    ]
