# Generated by Django 3.1.3 on 2021-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_activity_myactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myactivity',
            name='content',
        ),
        migrations.AddField(
            model_name='myactivity',
            name='title',
            field=models.TextField(default='', null=True, verbose_name='活動名稱'),
        ),
    ]
