# Generated by Django 3.1.3 on 2021-02-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210217_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myactivity',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='app.activity', verbose_name='活動名稱'),
        ),
    ]
